./float_finder.sh ../../data/patient11/statistics/data/statistics/
./float_finder.sh ../../data/patient12/statistics/data/statistics/
./float_finder.sh ../../data/patient4/statistics/data/statistics/
./float_finder.sh ../../data/patient5/statistics/data/statistics/
./float_finder.sh ../../data/patient13/statistics/data/statistics/
./float_finder.sh ../../data/patient14/statistics/data/statistics/
./float_finder.sh ../../data/patient16/statistics/data/statistics/
./float_finder.sh ../../data/patient18/statistics/data/statistics/
./float_finder.sh ../../data/patient30/statistics/data/statistics/
./float_finder.sh ../../data/patient9/statistics/data/statistics/